services:
  mysql:
    image: mysql:8.0
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      # 追加の設定ファイル
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql

  # Node.js（Express）
  app:
    image: node:18
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*  # デバッグモードを有効化
    tty: true  # 疑似ターミナルを割り当て
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm start  # コンテナ起動時に実行するコマンド
    depends_on:
      - mysql

networks:
  default:

volumes:
  mysqldata: