version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  express:
    build: .
    container_name: express-container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: myapp_user
      DB_PASSWORD: myapp_password
      DB_NAME: myapp_db
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: bash -c "if [ ! -f package.json ]; then express --view=ejs . && npm install; fi && npm start"

volumes:
  mysql-data: